In [24]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [25]:
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [27]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [28]:
## Define the vocabulary size
voc_size = 10000

In [29]:
#one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3820, 7105, 3503, 9484],
 [3820, 7105, 3503, 5497],
 [3820, 6742, 3503, 9054],
 [7814, 4951, 6950, 7354, 3528],
 [7814, 4951, 6950, 7354, 7844],
 [3462, 3820, 566, 3503, 2139],
 [967, 8207, 2286, 7354]]

In [30]:
## Word Embedding Represntation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [31]:
import numpy as np

In [32]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 3820, 7105, 3503, 9484],
       [   0,    0,    0,    0, 3820, 7105, 3503, 5497],
       [   0,    0,    0,    0, 3820, 6742, 3503, 9054],
       [   0,    0,    0, 7814, 4951, 6950, 7354, 3528],
       [   0,    0,    0, 7814, 4951, 6950, 7354, 7844],
       [   0,    0,    0, 3462, 3820,  566, 3503, 2139],
       [   0,    0,    0,    0,  967, 8207, 2286, 7354]])

In [33]:
# feature represntation
dim  = 10

In [36]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [37]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 209ms/step


array([[[-0.01094056, -0.02375809, -0.01554722,  0.00735126,
          0.00680216,  0.01214655,  0.02214351, -0.00483375,
         -0.04300945, -0.00745863],
        [-0.01094056, -0.02375809, -0.01554722,  0.00735126,
          0.00680216,  0.01214655,  0.02214351, -0.00483375,
         -0.04300945, -0.00745863],
        [-0.01094056, -0.02375809, -0.01554722,  0.00735126,
          0.00680216,  0.01214655,  0.02214351, -0.00483375,
         -0.04300945, -0.00745863],
        [-0.01094056, -0.02375809, -0.01554722,  0.00735126,
          0.00680216,  0.01214655,  0.02214351, -0.00483375,
         -0.04300945, -0.00745863],
        [-0.04501269, -0.00126791,  0.04435358,  0.03629551,
         -0.01134279, -0.04347431,  0.01744577,  0.00461958,
          0.03829556, -0.04900398],
        [-0.03713157, -0.02273962,  0.02580453,  0.04226707,
          0.01088367,  0.04643753, -0.00631861, -0.04554978,
          0.01315032,  0.01049274],
        [-0.01184194,  0.04236824, -0.0313589 , -0.0

In [41]:
embedded_docs[0]

array([   0,    0,    0,    0, 3820, 7105, 3503, 9484])